{
 "title": "Akka.NET Cluster + Phobos 2.1 Message Latency Metrics (Prometheus Data Source)",
 "description": "Message-processing latency dashboard for Akka.NET Clusters using Phobos 2.0 and OpenTelemetry.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "msgtype", "label": "msgtype", "query": { "query": "label_values(messagetype)" } },
   { "name": "actortype", "label": "actortype", "query": { "query": "label_values(actortype)" } }
  ]
 },
 "panels": [
  {
   "title": "[$msgtype] Cumulative Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Latency Over Time [$msgtype ]",
   "type": "heatmap",
   "description": "Heatmap of milliseconds of latency by $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(akka_messages_latency_milliseconds_bucket{messagetype=~\"$msgtype\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution [$msgtype ]",
   "type": "bargauge",
   "description": "Heatmap of milliseconds of latency by $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(akka_messages_latency_milliseconds_bucket{messagetype=~\"$msgtype\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[$msgtype] Latencies When Processed by [$actortype]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Latency Over Time [$actortype / $msgtype ]",
   "type": "heatmap",
   "description": "Heatmap of milliseconds of latency by $actortype / $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(akka_messages_latency_milliseconds_bucket{messagetype=~\"$msgtype\",actortype=~\"$actortype\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution [$actortype / $msgtype ]",
   "type": "bargauge",
   "description": "Heatmap of milliseconds of latency by $actortype / $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(akka_messages_latency_milliseconds_bucket{messagetype=~\"$msgtype\",actortype=~\"$actortype\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}