{
 "title": "Akka.NET Cluster + Phobos Metrics",
 "description": "System-wide Akka.NET metrics used for profiling Akka.NET performance. Gathered via Phobos and OpenTelemetry. Built for Phobos 2.x.",
 "tags": [
  "akka.net",
  "phobos"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(akka_actor_live_actors,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(akka_actor_live_actors{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "shardRegion",
    "label": "shardRegion",
    "query": {
     "query": "label_values(akka_cluster_sharding_shards{job=~\"$job\", instance=~\"$instance\"},region)"
    }
   },
   {
    "name": "actor_category",
    "label": "actor types",
    "query": {
     "query": "label_values(akka_actor_live_actors{job=~\"$job\"},actor_category)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Cluster Size",
   "type": "stat",
   "description": "Total number of active Akka.Cluster Members.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Up\",job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "Up"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"WeaklyUp\",job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "WeaklyUp"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Joining\",job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "Joining"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Leaving\",job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "Leaving"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Exiting\",job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "Exiting"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Down\",job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "stat",
   "description": "All nodes in the cluster that are detected to be unreachable.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\",job=~\"$job\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Cluster Nodes by Status",
   "type": "timeseries",
   "description": "Tracks all nodes by their membership status and reachability.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(avg by(status)(akka_cluster_members{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\",job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Akka.NET Instances",
   "type": "table",
   "description": "Status of all Akka.NET applications in the current job / instance. Current up to the minute.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (instance,akka_address, cluster_role, service_version, status) (\n  max_over_time(akka_cluster_members{job=~\"$job\",instance=~\"$instance\",status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[5m])\n) > 0",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(\r\n  sum by (instance) (\r\n    akka_actor_live_actors{job=~\"$job\", instance=~\"$instance\"}\r\n  )\r\n  and on (instance)\r\n  max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)\r\nor on (instance)\r\n(\r\n  0 * max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(\r\n  sum by (instance) (\r\n    rate(akka_messages_recv_msgs_total{job=~\"$job\", instance=~\"$instance\"}[$__range])\r\n  )\r\n  and on (instance)\r\n  max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)\r\nor on (instance)\r\n(\r\n  0 * max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(\r\n  sum by (instance) (\r\n    rate(akka_logs_events_total{job=~\"$job\", instance=~\"$instance\"}[$__range])\r\n  )\r\n  and on (instance)\r\n  max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)\r\nor on (instance)\r\n(\r\n  0 * max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(\r\n  sum by (instance) (\r\n    rate(akka_logs_events_total{level=\"error\", job=~\"$job\", instance=~\"$instance\"}[$__range])\r\n  )\r\n  and on (instance)\r\n  max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)\r\nor on (instance)\r\n(\r\n  0 * max by (instance) (\r\n    max_over_time(akka_cluster_members{job=~\"$job\", instance=~\"$instance\", status=~\"(Up|WeaklyUp|Joining|Leaving|Exiting)\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logging and Error Rates [$job]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster Logging Activity",
     "type": "timeseries",
     "description": "Total aggregate logging activity per-second for each node in an Akka.NET cluster.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(level)(ceil(irate(akka_logs_events_total{job=~\"$job\", instance=~\"$instance\"}[$__range])))",
       "legendFormat": "{{level}} / s"
      }
     ]
    },
    {
     "title": "Exceptions by Type",
     "type": "table",
     "description": "Groups all exceptions detected in Akka.NET logs by type.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, instance, akka_address, exceptiontype)(ceil(increase(akka_logs_events_total{job=~\"$job\", instance=~\"$instance\",exceptiontype=~\".+\"}[$__range])))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Total Errors Logged",
     "type": "stat",
     "description": "Total errors logged by Akka.NET over the time window.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(floor(increase(akka_logs_events_total{level=\"error\",job=~\"$job\", instance=~\"$instance\"}[$__range])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Actor Metrics [$job]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Actor Message Processing (msg/s)",
     "type": "timeseries",
     "description": "All actor message processing activity",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum by (actor_category)(ceil(irate(akka_messages_recv_msgs_total{job=~\"$job\", instance=~\"$instance\"}[$__range])))",
       "legendFormat": "{{actor_category}} msgs / second"
      },
      {
       "expr": "sum(ceil(irate(akka_messages_deadletters_msgs_total{job=~\"$job\", instance=~\"$instance\"}[$__range])))",
       "legendFormat": "{{actor_category}} deadletters / second"
      },
      {
       "expr": "sum(ceil(irate(akka_messages_unhandled_msgs_total{job=~\"$job\", instance=~\"$instance\"}[$__range])))",
       "legendFormat": "unhandled msgs / second"
      }
     ]
    },
    {
     "title": "Total Akka.NET Actors",
     "type": "timeseries",
     "description": "The full set of Akka.NET actors running on all nodes for all roles in a cluster.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance,akka_address,actor_category)(akka_actor_live_actors{job=~\"$job\", instance=~\"$instance\", actor_category=~\"$actor_category\"})",
       "legendFormat": "Total Actors [{{instance}} ({{actor_category}})]"
      }
     ]
    },
    {
     "title": "Actor Starts and Stops by Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by (actortype)(ceil(irate(akka_actor_created_starts_total{job=~\"$job\", instance=~\"$instance\", actor_category=~\"$actor_category\"}[$__range]))) != 0",
       "legendFormat": "{{actortype}} starts"
      },
      {
       "expr": "sum by (actortype)(ceil(irate(akka_actor_stopped_stops_total{job=~\"$job\",instance=\"$instance\",actor_category=~\"$actor_category\"}[$__range]))) != 0",
       "legendFormat": "{{actortype}} stopped"
      }
     ]
    },
    {
     "title": "Live Actors by Type",
     "type": "table",
     "description": "All actor counts by type.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "topk(10,sum by(actortype)(akka_actor_live_actors{job=~\"$job\", instance=~\"$instance\",actor_category=~\"$actor_category\"}))",
       "legendFormat": "{{actortype}} created"
      }
     ]
    },
    {
     "title": "Total Actor Throughput (msg/s)",
     "type": "stat",
     "description": "Cumulative Akka.NET messaging throughput across all selected nodes and roles.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (actor_category)(ceil(irate(akka_messages_recv_msgs_total{job=~\"$job\", instance=~\"$instance\"}[$__range])))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Akka.NET Message Throughput by Type  (Top 10)",
     "type": "bargauge",
     "description": "Akka.NET message throughput by message type.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by(messagetype)(rate(akka_messages_recv_msgs_total{job=~\"$job\", instance=~\"$instance\",actor_category=~\"$actor_category\"}[$__range])))",
       "legendFormat": "{{messagetype}}"
      }
     ]
    },
    {
     "title": "Akka.NET Message Totals by Type  (Top 10)",
     "type": "bargauge",
     "description": "Akka.NET message throughput by message type.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by(messagetype)(increase(akka_messages_recv_msgs_total{job=~\"$job\", instance=~\"$instance\",actor_category=~\"$actor_category\"}[$__range])))",
       "legendFormat": "{{messagetype}}"
      }
     ]
    },
    {
     "title": "Actor Crashes by Actor / Exception (Top 10)",
     "type": "table",
     "description": "Top 10 actor type / exception type pairs, based on the number of crashes per second observed over a 30 minute timespan.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "topk(10,sum by(actortype, exceptiontype)(rate(akka_actor_restarts_total{job=~\"$job\", instance=~\"$instance\",actor_category=~\"$actor_category\"}[$__range])))",
       "legendFormat": "{{actortype}},{{exceptiontype}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sharding Statistics [$shardRegion]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "shardRegion",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Shard Distribution [$shardRegion]",
     "type": "bargauge",
     "description": "Shows the distribution of $shardRegion shards across all nodes in the cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance)(akka_cluster_sharding_shards{region=~\"$shardRegion\",job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{akka_address}}"
      }
     ]
    },
    {
     "title": "Entity Distribution [$shardRegion]",
     "type": "bargauge",
     "description": "Shows the distribution of $shardRegion entities across all nodes in the cluster. Please note that this number reflects the total number of ALIVE entity actors.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance)(akka_cluster_sharding_entities{region=~\"$shardRegion\",job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}