{
 "title": "Akka.NET Cluster + Phobos 2.x Metrics (Prometheus Data Source)",
 "description": "System-wide Akka.NET metrics used for profiling Akka.NET performance. Gathered via Phobos and OpenTelemetry.",
 "tags": [
  "akka.net",
  "phobos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "role", "label": "Role", "query": { "query": "label_values(cluster_role)" } },
   { "name": "address", "label": "address", "query": { "query": "label_values(akka_address)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Cluster Size",
   "type": "stat",
   "description": "Total number of active Akka.Cluster Members.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Up\"}))",
     "legendFormat": "Up"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"WeaklyUp\"}))",
     "legendFormat": "WeaklyUp"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Joining\"}))",
     "legendFormat": "Joining"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Leaving\"}))",
     "legendFormat": "Leaving"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Exiting\"}))",
     "legendFormat": "Exiting"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Down\"}))",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "stat",
   "description": "All nodes in the cluster that are detected to be unreachable.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\"}))"
    }
   ]
  },
  {
   "title": "Cluster Nodes by Status",
   "type": "graph",
   "description": "Tracks all nodes by their membership status and reachability.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(avg by(status)(akka_cluster_members_members))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\"}))",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Logging and Error Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Logging Activity",
   "type": "graph",
   "description": "Total aggregate logging activity per-second for each node in an Akka.NET cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(increase(akka_logs_events{cluster_role=~\"$role\",akka_address=~\"$address\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Exceptions by Type (over 5m)",
   "type": "table-old",
   "description": "Groups all exceptions detected in Akka.NET logs by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address,exceptiontype)(ceil(increase(akka_logs_events{cluster_role=~\"$role\",akka_address=~\"$address\",exceptiontype=~\".+\"}[5m])))"
    }
   ]
  },
  {
   "title": "Total Errors Logged (5m)",
   "type": "stat",
   "description": "Total errors logged by Akka.NET over past 5 minutes, cumulative for all roles / cluster / exception types.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(akka_logs_events{level=\"error\",cluster_role=~\"$role\",akka_address=~\"$address\"}[5m]))"
    }
   ]
  },
  {
   "title": "Actor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "role",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Akka.NET Actors",
   "type": "graph",
   "description": "The full set of Akka.NET actors running on all nodes for all roles in a cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address)(akka_actor_created_starts{cluster_role=~\"$role\",akka_address=~\"$address\"}) - sum by(cluster_role,akka_address)(akka_actor_stopped_stops{cluster_role=~\"$role\",akka_address=~\"$address\"})",
     "legendFormat": "Total Actors [{{cluster_role}} ({{akka_address}})]"
    }
   ]
  },
  {
   "title": "Total Actor Throughput (msg/s)",
   "type": "stat",
   "description": "Cumulative Akka.NET messaging throughput across all selected nodes and roles.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(akka_messages_recv_msgs{cluster_role=~\"$role\",akka_address=~\"$address\"}[1m]))"
    }
   ]
  },
  {
   "title": "Live Actors by Type (Top 10)",
   "type": "table-old",
   "description": "Top 10 actor starts / stops by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype)(akka_actor_created_starts{cluster_role=~\"$role\",akka_address=~\"$address\"}))",
     "legendFormat": "{{actortype}} created"
    },
    {
     "expr": "topk(10,sum by(actortype)(akka_actor_stopped_stops{cluster_role=~\"$role\",akka_address=~\"$address\"}))",
     "legendFormat": "{{actortype}} terminated"
    }
   ]
  },
  {
   "title": "Actor Crashes by Actor / Exception (Top 10)",
   "type": "table",
   "description": "Top 10 actor type / exception type pairs, based on the number of crashes per second observed over a 30 minute timespan.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype, exceptiontype)(rate(akka_actor_restarts_restarts[30m])))",
     "legendFormat": "{{actortype}},{{exceptiontype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Throughput by Type  (Top 10)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(rate(akka_messages_recv_msgs{cluster_role=~\"$role\",akka_address=~\"$address\"}[5m])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Totals by Type  (Top 10 over 5 minutes)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(increase(akka_messages_recv_msgs{cluster_role=~\"$role\",akka_address=~\"$address\"}[5m])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  }
 ]
}