receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: :8889
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  logging:


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]      
      exporters: [logging]
      processors: [batch]
    metrics:
      receivers: [otlp]      
      exporters: [prometheus]
      processors: [batch] 